
INSERT INTO books (title, description, paruted_at, is_free, cover) VALUES
('Le monde de l''esclavage', 'Cet ouvrage d''une ambition exceptionnelle présente sous une forme accessible à un large public une histoire inédite de l''esclavage depuis la Préhistoire jusqu''au présent. Il paraît vingt ans après le vote de la loi Taubira, alors que la prise de conscience du passé esclavagiste est chaque jour plus aiguisée au sein de la société française.', '2021-08-19 00:00:00', 0, 'uploads/book_616830722a927.jpg'),
('Grand livre des 12 énergies', 'Alliez la puissance du conscient et de l''inconscient pour libérer profondément vos blocages énergétiques et cellulaires, avec des exercices et un soin énergétique en lecture méditative.Stéphanie Abellan, thérapeute, spécialisée dans la libération et le nettoyage cellulaire, propose un grand livre de pratiques pour libérer les blocages cellulaires. Car, au-delà du corps physique et psychique, notre santé repose aussi sur son aspect énergétique et sa mémoire cellulaire.', '2020-02-15 00:00:00', 0, 'uploads/book_616830bf465fe.jpg'),
('L''institut', 'En pleine nuit, à Minneapolis, des intrus pénètrent dans la maison de Luke Ellis, un surdoué de douze ans, tuent ses parents et le kidnappent. Quand le jeune garçon se réveille, à l''Institut, la chambre où il se trouve est semblable à la sienne – si ce n’est l’absence de fenêtre. Dans le couloir, d''autres portes cachent d''autres enfants, dotés comme lui de pouvoirs psychiques. Que font-ils là ? Qu''attend-on d''eux ? Et pourquoi ne cherchent-ils pas à s''enfuir ?', '2021-10-08 00:00:00', 1, 'uploads/book_6168312d8d8db.jpg'),
('La Vie invisible d''Addie Larue', 'Une vie dont personne ne se souviendra... Une histoire que vous ne pourrez plus jamais oublier...Une nuit de 1714, dans un moment de désespoir, une jeune femme avide de liberté scelle un pacte avec le diable. Mais si elle obtient le droit de vivre éternellement, en échange, personne ne pourra jamais plus se rappeler ni son nom ni son visage. La voilà condamnée à traverser les âges comme un fantôme, incapable de raconter son histoire, aussitôt effacée de la mémoire de tous ceux qui croisent sa route.', '2021-10-14 00:00:00', 0, 'uploads/book_6168315ea9ebe.jpg'),
('The Witcher Sorceleur - : Le Sorceleur : La carte de l''univers', 'L''univers médiéval fantastique du Sorceleur, historiquement équivalent à notre XVe siècle,  s''inspire des mythologies slave et nordique ainsi que des contes populaires. Sur la zone du Continent où se déroulent les aventures de Geralt de Riv, deux grands ensembles s''affrontent. Les Royaumes du Nord, une multitude de monarchies plus ou moins alliées, tentent de résister à un envahisseur aux motivations complexes, l''empire de Nilfgaard.', '2021-06-10 00:00:00', 1, 'uploads/book_616831c120b5d.jpg'),
('Dieu - La science Les preuves', 'Pendant près de quatre siècles, de Copernic à Freud en passant par Galilée et Darwin, les découvertes scientifiques se sont accumulées de façon spectaculaire, donnant l''impression qu''il était possible d''expliquer l''Univers sans avoir besoin de recourir à un dieu créateur. Et c''est ainsi qu''au début du XXe siècle, le matérialisme triomphait intellectuellement.', '2020-12-26 00:00:00', 1, 'uploads/book_6168320e6ccb3.jpg'),
('Ils sont passés à l''acte', 'Un père de famille aimant assassine ses deux filles, un brillant étudiant dévore sa petite amie, une adolescente révoltée fait exécuter ses parents, un groupe de collégiennes met à mort l’une d’entre elles… Résolues ou irrésolues, françaises ou internationales, cet ouvrage fait le récit glaçant de 13 affaires criminelles hors du commun vues de l’intérieur.', '2018-12-12 00:00:00', 1, 'uploads/book_6168329c2c8fd.jpg'),
('Louca - Tome 9 : Louca - Game Over', 'Louca et son coach fantôme Nathan sont bien décidés à reconstituer une équipe de foot digne de ce nom. Tant bien que mal, ils arrivent à recruter un bon nombre d''anciens coéquipiers de Nathan, en battant chacun d''eux dans son sport de prédilection (la fin justifiant les moyens, Louca n''hésite pas à se faire aider de manière éhontée par Nathan !).', '2010-10-10 00:00:00', 1, 'uploads/book_616832c35ee1c.jpg'),
('Astérix - Tome 39 : Astérix - Astérix et le Griffon', 'Astérix, Obélix et Idéfix sont de retour pour une 39e aventure. Accompagnés du plus célèbre des druides, ils s’apprêtent à partir pour un long voyage en quête d’une créature étrange et terrifiante.Mi-aigle, mi-lion, énigmatique à souhait, le Griffon sera l’objet de ce grand voyage ! Toujours réalisée par le talentueux duo formé par Jean-Yves Ferri au scénario et Didier Conrad au dessin, nul doute que cette nouvelle aventure proposera une quête épique et semée d’embûches à nos héros à la recherche de cet animal...', '2020-08-15 00:00:00', 0, 'uploads/book_616832fe65681.jpg');

INSERT INTO authors (name) VALUES ('John Doe'), ('Morgan Ortin'), ('Agnès Ledig'), ('Lucinda Riley'), ('Dora Mutot'), ('Olivier Bonnasies'), ('Jerome Pascalin'), ('Stephanie Abellin'), ('Michel-Yves Bolloré'), ('Stephen King');

INSERT INTO users (id, email, roles, password, lastname, firstname, address, birthdate) VALUES
('54381990-2cf7-11ec-9c98-309c23ed1c26', 'lanc@sar.fr', '[]', '$2y$13$5xnme/74h.wChOdLXdDn8OJbjYKx9lpeGDT1c06CRkZpAh9kxzh2K', 'Sarah', 'Lancaster', '48 avenue de la Mouette', '1994-09-05'),
('6f630271-2cf6-11ec-9c98-309c23ed1c26', 'john@doe.fr', '[]', '$2y$13$eaa1LbEAxZHHKV9uG9B16.WPM3W/1Hf3COCLlMa0XOEzc0bl9PNtS', 'John', 'Doe', '10 rue des palmiers', '2000-04-02'),
('960c82fe-2cf6-11ec-9c98-309c23ed1c26', 'maria@orvald.fr', '[]', '$2y$13$7mgE4O0ARQOurB2.qS6xa.wtK4riMTx5ZmR4bij3Y7w/DIpPutLqa', 'Maria', 'Orvald', '14 rue des Boulons', '1964-12-12'),
('a1331cb6-2873-11ec-a7e7-309c23ed1c26', 'admin@admin.fr', '["ROLE_EMPLOYEE"]', '$2y$13$aV2sTrKMIa3/gXMw8RMXHOux.nWqANkw9Xgh7AoNxTN9ywjNcyaqG', 'David', 'Webb', '8 rue du Plessis', '1996-02-14'),
('d71c4dc2-2cf7-11ec-9c98-309c23ed1c26', 'riul@dani.fr', '[]', '$2y$13$y93ExKCU3dbV.o5yQvOukuyFE/frRlICE/HiG/fZxOWRsQqXqmRFu', 'Daniel', 'Riul', '132 rue des coquelicots', '1945-05-28'),
('f533ec96-2cf6-11ec-9c98-309c23ed1c26', 'loiseau@marc.fr', '[]', '$2y$13$.LjPCr6x9SJzoP7Iso4kO.oe.x6BDLsnL.FiLlK3GcaqHez.XG8dq', 'Marc', 'Loiseau', '14 rue du citronnier', '1992-06-28');

INSERT INTO categories (name) VALUES
('Roman'), ('SF'), ('Histoire'), ('BD & Jeunesse'), ('Sciences'), ('Nature & Loisirs');

INSERT INTO books_authors (books_id, authors_id) VALUES (5, 4), (6, 6), (7, 5), (2, 10), (2, 2), (3, 8), (4, 3), (5, 9), (6, 1), (7, 4), (7, 6), (8, 3), (8, 9);

INSERT INTO books_categories (books_id, categories_id) VALUES
(1, 3), (1, 5), (2, 2), (2, 5), (2, 3), (3, 2), (4, 6), (5, 3), (5, 2), (6, 3), (6, 5), (7, 1), (8, 4), (9, 4);

INSERT INTO books_reservations (user_id, books_id, reserved_at, is_collected) VALUES ('a1331cb6-2873-11ec-a7e7-309c23ed1c26', 1, '2021-09-11 15:47:06', 1), ('960c82fe-2cf6-11ec-9c98-309c23ed1c26', 2, '2021-06-14 16:07:13', 1), ('960c82fe-2cf6-11ec-9c98-309c23ed1c26', 4, '2021-10-08 16:07:53', 1), ( 'd71c4dc2-2cf7-11ec-9c98-309c23ed1c26', 9, '2021-07-14 16:08:24', 1);